### PR TITLE
Add missing API calls for subscribeddomains and breacheddomain

### PR DESCRIPTION
**Pull request by freman**
Added under breaches because that's where they fall in the documentation
https://haveibeenpwned.com/API/v3#SubscribedDomains

### CODE REVIEW

**Comment by wneessen** [comment]
Thanks so much for the PR: I'm going to review it within the next few days. It's currently a bit busy over here.

**Comment by wneessen** [comment]
Hi again @freman,
the change looks good to me. Could you please also add corresponding tests?

**Comment by freman** [comment]
> Hi again @freman, the change looks good to me. Could you please also add corresponding tests?

Hey, so, I do have tests but they're not really portable, testing subscribeddomains is relatively easy, I just check to see if the provided key has any domains and make sure it's parsing the json but breacheddomain not so much. I've opened a support ticket to see if hibp-integration-tests.com could possibly be added for testing that api.

**Comment by freman** [comment]
I've pushed up some tests, this is Troy's response from HIBP

> If you vote on this idea, you'll receive a notification when it's implemented: https://haveibeenpwned.uservoice.com/forums/275398-general/suggestions/48189713-implement-test-api-key-for-automated-domain-search

**Comment by wneessen** [comment]
> I've pushed up some tests, this is Troy's response from HIBP
> 
> > If you vote on this idea, you'll receive a notification when it's implemented: https://haveibeenpwned.uservoice.com/forums/275398-general/suggestions/48189713-implement-test-api-key-for-automated-domain-search

Yeah, that's the answer I got for my last request as well ;) Thanks for trying anyways. The PR looks good to me and will be merged today. I'll probably issue a new release during the weekend.

**Pull request merged**
